# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com

service: inside-vpc

plugins:
  - serverless-plugin-typescript
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  timeout: 30
  region: ap-southeast-2
  vpc:
    securityGroupIds:
      - sg-4d4b742b
    subnetIds:
      - subnet-44646e1d
      - subnet-a865decf
      - subnet-f565d0bc
  apiKeys:
    - Demo
    - DrFriendless

custom:
  secret: ${file(../secrets.json)}
  customDomain:
    domainName: api.drfriendless.com
    basePath: 'v1'
    stage: ${self:provider.stage}
    createRoute53Record: false
    certificateName: "api.drfriendless.com"

functions:
  writeToDB:
    handler: functions.writeToDB
    environment:
      mysqlHost: ${self:custom.secret.mysqlHost}
      mysqlUsername: ${self:custom.secret.mysqlUsername}
      mysqlPassword: ${self:custom.secret.mysqlPassword}
      mysqlDatabase: ${self:custom.secret.mysqlDatabase}
    events:
      - sns: ${cf:outside-vpc-dev.UserListNotificationTopic}
    role:
        "doStuffFromInsideVPC"
  userlistFunction:
    handler: functions.userlist
    environment:
      mysqlHost: ${self:custom.secret.mysqlHost}
      mysqlUsername: ${self:custom.secret.mysqlUsername}
      mysqlPassword: ${self:custom.secret.mysqlPassword}
      mysqlDatabase: ${self:custom.secret.mysqlDatabase}
    events:
      - http:
          path: users
          method: post
          cors: true
          integration: lambda
          private: true
      - http:
          path: users
          method: get
          cors: true
          integration: lambda
          private: true
    role:
        "doStuffFromInsideVPC"
  toProcessFunction:
    handler: functions.toProcess
    environment:
      mysqlHost: ${self:custom.secret.mysqlHost}
      mysqlUsername: ${self:custom.secret.mysqlUsername}
      mysqlPassword: ${self:custom.secret.mysqlPassword}
      mysqlDatabase: ${self:custom.secret.mysqlDatabase}
    events:
      - http:
          path: toProcess
          method: post
          cors: true
          integration: lambda
          private: true
      - http:
          path: toProcess
          method: get
          cors: true
          integration: lambda
          private: true
    role:
        "doStuffFromInsideVPC"

resources:
  Resources:
    doStuffFromInsideVPC:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: doStuffFromInsideVPCPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      - - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DetachNetworkInterface
                    - ec2:DeleteNetworkInterface
                  Resource: "*"
