service: inside

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  timeout: 30
  memorySize: 128
  region: ap-southeast-2
  vpc:
    securityGroupIds:
      - sg-4d4b742b
    subnetIds:
      - subnet-44646e1d
      - subnet-a865decf
      - subnet-f565d0bc

custom:
  secret: ${file(../secrets.json)}
  database: ${file(../database.json)}

functions:
  updateUserList:
    handler: functions.updateUserList
    timeout: 120
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  processUserResult:
    handler: functions.processUserResult
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  updateGameAsDoesNotExist:
    handler: functions.updateGameAsDoesNotExist
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  processGameResult:
    handler: functions.processGameResult
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  processCollectionRestrictToIDs:
    handler: functions.processCollectionRestrictToIDs
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  processCollectionUpdateGames:
    handler: functions.processCollectionUpdateGames
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  processCollectionCleanup:
    handler: functions.processCollectionCleanup
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  processPlayedMonthsResult:
    handler: functions.processPlayedMonths
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  processPlaysResult:
    handler: functions.processPlaysResult
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  updateUrlAsProcessed:
    handler: functions.updateUrlAsProcessed
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  updateUrlAsUnprocessed:
    handler: functions.updateUrlAsUnprocessed
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  updateUrlAsTryTomorrow:
    handler: functions.updateUrlAsTryTomorrow
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
  updateRankings:
    handler: functions.updateRankings
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    role:
        "doStuffFromInsideVPC"
    events:
      - schedule:
          name: updateRankings
          description: every day, calculate normalised ranking and ext top 100
          rate: rate(24 hours)
          enabled: true
          input:
            stageParams:
              stage: dev
  getToProcessList:
    handler: functions.getToProcessList
    environment:
      mysqlHost: ${self:custom.database.mysqlHost}
      mysqlUsername: ${self:custom.database.mysqlUsername}
      mysqlPassword: ${self:custom.database.mysqlPassword}
      mysqlDatabase: ${self:custom.database.mysqlDatabase}
    events:
      - http:
          path: toProcess
          method: post
          cors: true
          integration: lambda
          private: true
      - http:
          path: toProcess
          method: get
          cors: true
          integration: lambda
          private: true
    role:
        "doStuffFromInsideVPC"

resources:
  Resources:
    doStuffFromInsideVPC:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: doStuffFromInsideVPCPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      - - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DetachNetworkInterface
                    - ec2:DeleteNetworkInterface
                  Resource: "*"
