service: downloader

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2
  timeout: 30
  memorySize: 128

custom:
  secret: ${file(../secrets.json)}

functions:
  processUserList:
    handler: functions.processUserList
    environment:
      USERS_FILE: ${self:custom.secret.usersFile}
    role:
      "invokeLambdas"
    events:
      - schedule:
          name: lookForNewUsers
          description: every hour, look to see if new users have been added
          rate: rate(60 minutes)
          enabled: true
          input:
            stageParams:
              stage: dev
  fireFileProcessing:
    handler: functions.fireFileProcessing
    role:
      "invokeLambdas"
    events:
      - schedule:
          name: processFiles
          description: every 10 minutes, look to see if there are files to process
          rate: rate(1 minute)
          enabled: true
          input:
            count: 10
            stageParams:
              stage: dev
  processUser:
    handler: functions.processUser
    role:
      "invokeLambdas"
  processGame:
    handler: functions.processGame
    role:
      "invokeLambdas"
  processPlayed:
    handler: functions.processPlayed
    role:
      "invokeLambdas"
  processPlays:
    handler: functions.processPlays
    role:
      "invokeLambdas"
  processCollection:
    handler: functions.processCollection
    timeout: 300
    memorySize: 256
    role:
      "invokeLambdas"

resources:
  Resources:
    invokeLambdas:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: invokeLambdasPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      - - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DetachNetworkInterface
                    - ec2:DeleteNetworkInterface
                  Resource: "*"

