# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: users-from-pastebin

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        Ref: "UserListNotification"

functions:
  readFromPastebin:
    handler: functions.readFromPastebin
    environment:
      SNS_ENDPOINT:
         Ref: "UserListNotification"

resources:
  Resources:
    UserListNotification:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "userlists"
    ProcessUserNotification:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "processUser"
  Outputs:
    UserListNotificationTopic:
      Description: "SNS topic that new lists of users arrive on."
      Value:
        Ref: "UserListNotification"
      Export:
        Name: "UserListNotificationTopic"
    ProcessUserNotificationTopic:
      Description: "SNS topic for usernames of users whose profile should be retrieved."
      Value:
        Ref: "ProcessUserNotification"
      Export:
        Name: "ProcessUserNotificationTopic"

